### ISSUE TITLE
HTML Syntax (PT)

### ISSUE THREAD

**Issue by AniLeo** [literalmente-game/literalmente-game.github.io#1]
Os browsers modernos infelizmente ignoram erros de sintaxe HTML, alguns deles graves, e que podem - ou não - causar problemas eventualmente. Isto, na minha opinião, é meio ruim para quem está aprendendo HTML, pois pode dar origem a maus hábitos, mas felizmente existem formas de manter a sintaxe correta.

Recomendo validar o seu código após alterações utilizando:

- **HTML:** https://validator.w3.org/
- **CSS:** http://www.css-validator.org/

Atualmente a página tem alguns erros como:

**BOM found in UTF-8 File:** Esse é um erro meio bobo. O BOM é um "espaço" extra que é colocado no início do ficheiro, e que pode dar problemas de espaçamento na própria página sem você dar conta, eu meio que buguei a minha lista faz uns dias quando sem querer codifiquei um ficheiro com BOM. 
Para corrigir, é só ir no Notepad++ em Encoding e selecionar a opção UTF-8 (sem BOM), em todos os ficheiros afetados. Até hoje ainda não descobri uma utilidade prática para o raio do BOM.
![image](https://user-images.githubusercontent.com/10283761/28140002-7aebc86e-674e-11e7-9cd6-9d97a405d392.png)

**Charset:** Falta de declaração do charset. Isto pode causar problemas de acentuação. Basta adicionar ``<meta charset="UTF-8">`` no head.

**Doctype:** Falta de declaração do tipo de documento. Isto deve ser declarado bem no inicio do ficheiro, antes da abertura da tag HTML. Só adicionar ``<!DOCTYPE html>``.

O resto são typos que você consegue pegar facilmente com os validators. 

Mais recursos:
- https://www.w3schools.com/html/default.asp
- http://devdocs.io/html/

Bom estudo e continuação de trabalho fazendo essa lista para o CXBX-Reloaded!

**Comment by literalmente-game** [comment]
Muito obrigado por todas as orientações e observações, vão ajudar bastante. 

Com relação ao UTF-8 acabei notando logo depois de realizar o upload do primeiro documento contendo um acento (na palavra "Jogável"), como apareceu um símbolo no lugar da letra fui logo atrás e agora todos os documentos já estão utilizando UTF-8 e o texto aparece como deveria. A declaração do charset agora está presente em todos os arquivos também (mas vou re-editar tudo novamente quando a maioria dos items estiver nas listas). 

Vou tentar simplificar o código e usar os links que você deixou como referência, teria mais alguma observação antes de eu fechar essa issue ?

**Comment by AniLeo** [comment]
Não lembro de mais nada, recomendação principal é manter um olho na sintaxe em cada página, optimizações e simplificações no código você facilmente pega com o tempo.

Fechando!
